# create a postgres instance with docker compose
version: "3.8"

services:
  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: markdown-notes
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
